#!/usr/bin/env bash
# Generate staged Prisma migrations (one folder per logical stage) using
# `prisma migrate diff` between consecutive staged schemas.
#
# No database connection is required: diffs are computed from the schema files
# themselves, so this is safe to run on a clean checkout.
#
# Usage:  scripts/generate-migrations-diff.sh [--clean]
#           --clean   remove prisma/migrations/* first (default: keep existing)

set -euo pipefail

cd "$(dirname "$0")/.."

MIGRATIONS_DIR="prisma/migrations"
STAGED_DIR="prisma/staged-schemas"
SCHEMA="prisma/schema.prisma"

if [[ ! -d "$STAGED_DIR" ]]; then
  echo "Missing $STAGED_DIR" >&2
  exit 1
fi

if [[ "${1:-}" == "--clean" ]]; then
  echo "Cleaning $MIGRATIONS_DIR ..."
  find "$MIGRATIONS_DIR" -mindepth 1 -maxdepth 1 -type d -exec rm -rf {} +
fi

# Ordered stage list: file stem : human readable name
STAGES=(
  "01_auth_rbac:auth_rbac"
  "02_vendor:vendor"
  "03_category_product:category_product"
  "04_cart_order:cart_order"
  "05_transaction:transaction"
  "06_review_coupon:review_coupon"
  "07_chat:chat"
  "08_storage_notification:storage_notification"
  "09_infra:infra"
  "10_shipping:shipping"
  "11_otp:otp"
)

# Prisma migration lock file (single canonical lock per provider)
cat > "$MIGRATIONS_DIR/migration_lock.toml" <<'ENDLOCK'
# Please do not edit this file manually
# It should be added in your version-control system (i.e. Git)
provider = "postgresql"
ENDLOCK

base_epoch="${STAGED_BASE_TIMESTAMP:-$(date +%s)}"
if ! date -d "@$base_epoch" >/dev/null 2>&1; then
  base_epoch="$(date +%s)"
fi
prev_schema=""
index=0

for stage_pair in "${STAGES[@]}"; do
  IFS=':' read -r stage_file migration_name <<<"$stage_pair"
  staged_path="$STAGED_DIR/${stage_file}.prisma"

  if [[ ! -f "$staged_path" ]]; then
    echo "✗ Missing staged schema: $staged_path" >&2
    exit 1
  fi

  index=$((index + 1))
  # Deterministic, strictly increasing timestamps: +1s per stage from the base
  stamp="$(date -d "@$((base_epoch + index))" +%Y%m%d%H%M%S)"
  migration_dir="$MIGRATIONS_DIR/${stamp}_${migration_name}"
  mkdir -p "$migration_dir"

if [[ "$index" -eq 1 ]]; then
  # First stage builds every table from scratch.
  npx prisma migrate diff \
    --from-empty \
    --to-schema-datamodel "$staged_path" \
    --script >"$migration_dir/migration.sql"
else
  npx prisma migrate diff \
    --from-schema-datamodel "$prev_schema" \
    --to-schema-datamodel "$staged_path" \
    --script >"$migration_dir/migration.sql"
fi

  if [[ ! -s "$migration_dir/migration.sql" ]]; then
    rm -rf "$migration_dir"
    echo "= Stage $stage_file produced no changes, skipped"
    prev_schema="$staged_path"
    continue
  fi

  table_count=$(grep -cE '^(CREATE TABLE|ALTER TABLE|CREATE TYPE|DROP TABLE)' "$migration_dir/migration.sql" || true)
  echo "✓ ${migration_name}: $(basename "$migration_dir") (${table_count} statements)"
  prev_schema="$staged_path"
done

# The final staged schema must produce no diff against the live schema.
final_sql="$(mktemp)"
trap 'rm -f "$final_sql"' EXIT
npx prisma migrate diff \
  --from-schema-datamodel "$STAGED_DIR/11_otp.prisma" \
  --to-schema-datamodel "$SCHEMA" \
  --script >"$final_sql" 2>/dev/null || true

if grep -qvE '^\s*(--.*)?$' "$final_sql"; then
  echo ""
  echo "⚠ Warning: $SCHEMA has drifted from the final staged schema."
  echo "  Run:  node scripts/generate-staged-schemas.mjs && npx prisma format"
fi

echo ""
echo "=== Migrations generated ==="
ls -1 "$MIGRATIONS_DIR"
echo ""
echo "Apply with:  npx prisma migrate deploy"
